package com.forum.models;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.JsonNode;

import java.util.List;
import java.util.ArrayList;

/**
 * Post is a Data Transfer Object (DTO) / Model representing a single discussion post 
 * or reply within a specific topic in the Smart Discussion Forum application.
 * 
 * <p><b>Architectural Role:</b>
 * This class serves as the fundamental building block for threaded discussions. 
 * Unlike flat data models, {@code Post} is explicitly designed to support a recursive, 
 * hierarchical tree structure. After being fetched from the API, instances of this class 
 * are processed by the controller's {@code buildReplyTree} algorithm to nest child replies 
 * within their respective parent {@code replies} lists, enabling the UI to render deeply 
 * nested comment threads.
 * 
 * <p><b>JSON Deserialization Strategy:</b>
 * <ul>
 *   <li>{@link JsonIgnoreProperties}: Configured with {@code ignoreUnknown = true} to ensure 
 *       forward compatibility with backend API changes without causing deserialization crashes.</li>
 *   <li>{@link JsonProperty}: Used to explicitly map Java camelCase field names (like {@code parentId}) 
 *       to the backend's snake_case JSON keys (like {@code "parent_id"}), maintaining clean Java 
 *       naming conventions while ensuring accurate data binding.</li>
 *   <li>{@link JsonNode}: Used for complex or dynamic JSON structures (like {@code author} and 
 *       {@code excluded_users}) where a strict POJO might be too rigid or where lazy, defensive 
 *       parsing is preferred to prevent crashes on malformed backend data.</li>
 * </ul>
 * 
 * @author Forum Development Team
 * @version 2.0
 * @see com.forum.controllers.MainController
 * @see com.forum.services.ApiService
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Post {

    // =========================================================================
    // ─── CORE IDENTIFIERS & METADATA ─────────────────────────────────────────
    // =========================================================================

    /**
     * The unique numerical identifier for this post, assigned by the backend database.
     * <p><b>Note:</b> For offline drafts, this may temporarily hold a negative local ID 
     * generated by the {@code DatabaseHandler} until it is synced and replaced by a server ID.
     */
    public int id;

    /**
     * The numerical identifier of the {@link Topic} to which this post belongs.
     * Used to scope API requests and database queries to a specific discussion thread.
     */
    public int topic_id;

    /**
     * The numerical identifier of the {@link User} who authored this post.
     */
    public int user_id;

    /**
     * The main textual content of the post. 
     * May contain plain text or formatted markdown depending on the frontend rendering implementation.
     */
    public String content;

    /**
     * A flag indicating whether this post is marked as private.
     * <p><b>Business Logic:</b> If {@code true}, the post's visibility is restricted based on 
     * the users listed in the {@link #excluded_users} array.
     */
    public boolean is_private;

    /**
     * The ISO 8601 formatted timestamp indicating when this post was created on the server.
     * Example format: "2023-10-27T10:00:00Z"
     */
    public String created_at;

    // =========================================================================
    // ─── COMPLEX / DYNAMIC JSON FIELDS ───────────────────────────────────────
    // =========================================================================

    /**
     * A dynamic JSON node representing the author of the post.
     * <p><b>Design Choice:</b> Instead of a strict {@code User} object, a {@link JsonNode} is used here 
     * to safely extract specific fields (like {@code "name"}) without failing if the backend 
     * returns a partial user object, a deleted user placeholder, or a slightly different schema.
     */
    public JsonNode author;

    /**
     * A dynamic JSON array node containing the user objects or IDs that are explicitly 
     * excluded from viewing this post (applicable only when {@link #is_private} is {@code true}).
     */
    public JsonNode excluded_users;

    // =========================================================================
    // ─── ENGAGEMENT & ANALYTICS ──────────────────────────────────────────────
    // =========================================================================

    /**
     * The total number of likes this post has received.
     * <p><b>Note:</b> Wrapped in an {@link Integer} object (rather than primitive {@code int}) 
     * to safely handle {@code null} values from the API before the post receives its first like.
     */
    public Integer likes_count;

    /**
     * A flag indicating whether the currently authenticated user has liked this post.
     * <p><b>Note:</b> Wrapped in a {@link Boolean} object to safely handle {@code null} states 
     * for unauthenticated users or before the like status is resolved by the API.
     */
    public Boolean is_liked;

    // =========================================================================
    // ─── HIERARCHICAL STRUCTURE (NESTED REPLIES) ─────────────────────────────
    // =========================================================================

    /**
     * The ID of the parent post that this post is replying to.
     * <p><b>Business Logic:</b> 
     * <ul>
     *   <li>{@code null} or {@code 0}: Indicates this is a top-level post directly under a Topic.</li>
     *   <li>{@code > 0}: Indicates this is a nested reply, and this value points to the {@link #id} of the parent.</li>
     * </ul>
     * <p><b>JSON Mapping:</b> Explicitly mapped from the backend's snake_case key {@code "parent_id"}.
     */
    @JsonProperty("parent_id")
    public Integer parentId;

    /**
     * A list of child posts that are direct replies to this post.
     * <p><b>Initialization:</b> This list is populated <i>after</i> the initial API fetch by the 
     * controller's {@code buildReplyTree} algorithm, which iterates through flat posts and nests 
     * them into their respective parent's {@code replies} collection to form the UI tree.
     */
    public List<Post> replies;

    // =========================================================================
    // ─── CONSTRUCTORS ────────────────────────────────────────────────────────
    // =========================================================================

    /**
     * Default no-argument constructor required by Jackson for JSON deserialization.
     * <p><b>Safety Measure:</b> Proactively initializes the {@link #replies} list to an empty 
     * {@link ArrayList} to prevent {@code NullPointerException} when the controller attempts 
     * to add child replies during the tree-building phase, even if the JSON payload omits the field.
     */
    public Post() {
        this.replies = new ArrayList<>();
    }

    // =========================================================================
    // ─── HELPER METHODS ──────────────────────────────────────────────────────
    // =========================================================================

    /**
     * Safely parses the {@link #excluded_users} JSON node and extracts a list of integer user IDs.
     * 
     * <p><b>Defensive Programming:</b> 
     * This method includes null checks and type validation ({@code isArray()}) to ensure that 
     * malformed, missing, or unexpected JSON data from the backend does not crash the application.
     * 
     * @return A {@link List} of {@link Integer} representing the IDs of excluded users. 
     *         Returns an empty list if {@code excluded_users} is null, not an array, or empty.
     */
    public List<Integer> getExcludedUserIds() {
        // Guard clause: Ensure the node exists and is actually a JSON array
        if (excluded_users == null || !excluded_users.isArray()) {
            return new ArrayList<>();
        }
        
        List<Integer> ids = new ArrayList<>();
        
        // Safely iterate through the JSON array and extract the "id" field from each object
        for (JsonNode node : excluded_users) {
            if (node.has("id")) {
                ids.add(node.path("id").asInt());
            }
        }
        
        return ids;
    }

    /**
     * Convenience method to determine if this post is a top-level post (i.e., a direct 
     * response to the Topic, rather than a nested reply to another post).
     * 
     * @return {@code true} if {@link #parentId} is {@code null} or {@code 0}, {@code false} otherwise.
     */
    public boolean isTopLevel() {
        return parentId == null || parentId == 0;
    }
}