/**
 * Package: com.forum.models
 * 
 * This package contains the core domain models and data transfer objects (DTOs) 
 * used throughout the forum application. Classes in this package are primarily 
 * responsible for representing the state of business entities, facilitating 
 * data binding from JSON payloads (via Jackson), and mapping to database records.
 */
package com.forum.models;

/**
 * Jackson annotation used to indicate that unknown properties in the incoming 
 * JSON payload should be ignored during deserialization. 
 * 
 * Architectural Note: This is a critical resilience pattern. It ensures that if 
 * the API client sends additional fields (or if the frontend evolves to send 
 * newer fields), the backend deserialization will not fail with an 
 * UnrecognizedPropertyException. This provides forward and backward compatibility 
 * for the API contract.
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Jackson annotation used to explicitly map a JSON property name to a Java field.
 * 
 * Architectural Note: This is used here to bridge the gap between standard 
 * Java naming conventions (camelCase) and standard JSON/API naming conventions 
 * (snake_case). This ensures the API remains RESTful and consistent with 
 * typical JSON schema designs while keeping the Java codebase idiomatic.
 */
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Represents a single, discrete attempt made by a user to complete a Quiz.
 * 
 * This model serves a dual purpose within the application architecture:
 * 1. Detailed View: It can hold a fully populated nested {@link Quiz} object 
 *    when returning detailed information about a specific, individual attempt.
 * 2. Lightweight List View: It contains denormalized fields (such as 
 *    {@link #quizTitle} and {@link #totalQuestions}) to optimize payload size 
 *    when returning a list of historical attempts, preventing the need for 
 *    expensive joins or over-fetching of the full {@link Quiz} entity.
 * 
 * Serialization Behavior:
 * - Unknown JSON properties are safely ignored (@JsonIgnoreProperties).
 * - Specific fields are explicitly mapped to snake_case JSON keys to maintain 
 *   a consistent external API contract.
 * 
 * @see Quiz
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QuizAttempt {

    /**
     * The unique, primary identifier for this specific quiz attempt record.
     * 
     * This ID is typically generated by the database (e.g., auto-incrementing 
     * integer or sequence) and is used to uniquely reference this exact attempt 
     * in API endpoints, database queries, and audit logs.
     */
    public int id;

    /**
     * The timestamp indicating the exact moment the user initiated this quiz attempt.
     * 
     * JSON Mapping: "started_at"
     * Expected Format: Typically an ISO 8601 formatted string (e.g., "2023-10-27T10:00:00Z") 
     * or a server-standardized date string. This is crucial for calculating 
     * time-to-complete, enforcing time limits, and auditing user activity.
     */
    @JsonProperty("started_at")
    public String startedAt;

    /**
     * The total time taken by the user to complete this quiz attempt, measured in seconds.
     * 
     * JSON Mapping: "duration_seconds"
     * Usage: This value is used to evaluate performance, enforce maximum time 
     * limits, and display time-spent metrics on the user's dashboard. 
     * Storing this as an integer in seconds avoids timezone complexities 
     * associated with storing end-time timestamps.
     */
    @JsonProperty("duration_seconds")
    public int durationSeconds;

    /**
     * A nested object representing the full details of the quiz that was attempted.
     * 
     * Usage Context: This field is typically populated when the API is returning 
     * a detailed, single-record view of a quiz attempt. 
     * 
     * Performance Note: In list-based API responses (e.g., "Get all my attempts"), 
     * this field may be intentionally left null or omitted to reduce payload size 
     * and prevent N+1 query problems, relying instead on the denormalized fields 
     * below (quizTitle, totalQuestions) for display purposes.
     */
    public Quiz quiz;

    /* =========================================================================
     * DENORMALIZED FIELDS FOR OPTIMIZED LIST VIEWS
     * 
     * The following fields are intentionally duplicated/denormalized from the 
     * nested {@link Quiz} object. This is a deliberate performance optimization 
     * to support lightweight "Attempt History" list endpoints without requiring 
     * the backend to fetch and serialize the entire Quiz entity for every row.
     * =========================================================================
     */

    /**
     * The title of the quiz associated with this attempt.
     * 
     * JSON Mapping: "quiz_title"
     * Purpose: Provides a quick, human-readable reference to the quiz in list 
     * views without requiring the client to traverse the nested {@link #quiz} 
     * object or make additional API calls to fetch quiz metadata.
     */
    @JsonProperty("quiz_title")
    public String quizTitle;

    /**
     * The numerical score achieved by the user in this specific quiz attempt.
     * 
     * Purpose: Represents the final evaluated result of the attempt. The scale 
     * or meaning of this score (e.g., percentage, raw points) is typically 
     * contextualized by the {@link #totalQuestions} field or the associated 
     * Quiz grading rubric.
     */
    public int score;

    /**
     * The total number of questions that were presented in this quiz attempt.
     * 
     * JSON Mapping: "total_questions"
     * Purpose: Essential for calculating the percentage score (score / totalQuestions) 
     * on the frontend. It is stored here because the total number of questions 
     * might vary between different versions of a quiz, so capturing it at the 
     * time of the attempt ensures historical accuracy in reporting.
     */
    @JsonProperty("total_questions")
    public int totalQuestions;

    /**
     * A human-readable or formatted date string representing when this attempt 
     * occurred or was completed.
     * 
     * Purpose: While {@link #startedAt} provides the precise technical timestamp, 
     * this field is often formatted specifically for direct display in the UI 
     * (e.g., "Oct 27, 2023" or "2 days ago"). It may be populated by the backend 
     * formatter or the frontend based on the started_at timestamp, depending on 
     * the specific API implementation.
     */
    public String date;
}