/**
 * Package: com.forum.models
 * 
 * This package contains the core domain models and data transfer objects (DTOs) 
 * used throughout the forum application. Classes in this package are primarily 
 * responsible for representing the state of business entities, facilitating 
 * data binding from JSON payloads (via Jackson), and mapping to database records.
 */
package com.forum.models;

/**
 * Jackson annotation used to indicate that unknown properties in the incoming 
 * JSON payload should be ignored during deserialization.
 * 
 * Architectural Note: This is a critical resilience pattern for forum APIs. 
 * It ensures that if the frontend sends additional metadata, or if external 
 * services append new fields to the topic payload, the backend deserialization 
 * will not fail with an UnrecognizedPropertyException. This guarantees forward 
 * and backward compatibility for the API contract.
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Jackson annotation used to explicitly map a JSON property name to a Java field.
 * 
 * Architectural Note: This bridges the gap between standard Java naming 
 * conventions (camelCase) and standard JSON/database naming conventions 
 * (snake_case). This ensures the external API remains RESTful and consistent 
 * with typical JSON schema designs while keeping the internal Java codebase idiomatic.
 */
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Jackson JsonNode represents a generic, tree-model JSON node.
 * 
 * Architectural Note: Using JsonNode for the 'creator' field provides deliberate 
 * schema flexibility. In a forum system, the creator's payload might vary 
 * depending on the endpoint (e.g., a lightweight summary in a topic list vs. 
 * a full user profile in a detailed view). Using JsonNode prevents strict 
 * coupling to a specific User class here, allowing the backend to pass through 
 * whatever creator representation the database or aggregation layer provides 
 * without triggering deserialization errors.
 */
import com.fasterxml.jackson.databind.JsonNode;

/**
 * Represents a discussion Topic within the forum application.
 * 
 * A Topic serves as the primary container for a threaded conversation. It is 
 * logically grouped under a specific category or community (via group_id) and 
 * contains the foundational metadata required to render topic lists, detail 
 * views, and analytics dashboards.
 * 
 * Key Architectural Patterns in this Model:
 * 1. Denormalization: Fields like 'postsCount' are intentionally denormalized 
 *    to optimize read-heavy list views, preventing expensive COUNT(*) database 
 *    queries on the associated posts/replies table.
 * 2. Flexible Polymorphism: The 'creator' field utilizes a generic JsonNode to 
 *    accommodate varying levels of user detail without breaking the API contract.
 * 3. ML Integration: The 'mlCategory' field indicates support for machine-learning 
 *    driven auto-classification or content tagging, decoupling AI metadata from 
 *    the core business logic.
 * 
 * Serialization Behavior:
 * - Unknown JSON properties are safely ignored (@JsonIgnoreProperties).
 * - Specific fields are explicitly mapped to snake_case JSON keys to maintain 
 *   a consistent external API contract.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Topic {

    /**
     * The unique, primary identifier for this topic.
     * 
     * Purpose: Typically generated by the database (e.g., auto-incrementing 
     * integer or sequence). This ID is used to uniquely reference this topic 
     * in API endpoints (e.g., /topics/{id}), database queries, and routing.
     */
    public int id;

    /**
     * The identifier of the group, category, or forum section to which this topic belongs.
     * 
     * Purpose: Acts as a logical foreign key. It is used to filter, sort, and 
     * aggregate topics within specific community boundaries. Keeping this as a 
     * primitive int ensures fast indexing and efficient database joins.
     */
    public int group_id;

    /**
     * The main title or subject line of the discussion topic.
     * 
     * Purpose: This is the primary human-readable identifier for the topic. 
     * It is prominently displayed in topic lists, search results, and browser 
     * titles. It should be concise yet descriptive enough to summarize the 
     * discussion's core theme.
     */
    public String title;

    /**
     * The detailed body, summary, or opening description of the topic.
     * 
     * Purpose: Provides the initial context for the discussion. Depending on 
     * the frontend implementation, this may contain plain text or sanitized 
     * HTML/Markdown. It is displayed in the topic detail view to inform users 
     * about the purpose of the thread before they read individual replies.
     */
    public String description;

    /**
     * The numeric identifier of the user who originally created this topic.
     * 
     * Purpose: Stored as a primitive int for fast database indexing and 
     * efficient joins with the user table. This is distinct from the nested 
     * 'creator' object, as this ID is always required for authorization checks 
     * (e.g., "Can this user edit/delete the topic?") regardless of whether 
     * the full creator profile is loaded.
     */
    public int creator_id;

    /**
     * The timestamp indicating when this topic was initially created.
     * 
     * Expected Format: Typically an ISO 8601 formatted string 
     * (e.g., "2023-10-27T10:00:00Z"). 
     * Purpose: Used for sorting topic lists (e.g., "Newest First"), displaying 
     * relative time to users (e.g., "2 days ago"), and auditing content lifecycle.
     */
    public String created_at;

    /**
     * A flexible, tree-model JSON representation of the topic's creator.
     * 
     * Architectural Note: This is intentionally typed as JsonNode rather than 
     * a strict User class. This allows the API to return varying levels of 
     * creator detail (e.g., just {id, username, avatar} in a list view, vs. 
     * a full profile object in a detail view) without requiring multiple DTO 
     * classes or risking deserialization failures if the user payload shape 
     * changes.
     */
    public JsonNode creator;

    /**
     * The machine-learning derived category or tag assigned to this topic.
     * 
     * JSON Mapping: "ml_category"
     * Purpose: Represents the output of an NLP or classification model that 
     * automatically analyzes the topic's title and description to assign a 
     * category. This is useful for automated content routing, spam detection, 
     * or recommending related topics, decoupling AI-driven metadata from 
     * manual user-selected categories.
     */
    @JsonProperty("ml_category")
    public String mlCategory;

    /**
     * The total number of posts or replies associated with this topic.
     * 
     * JSON Mapping: "posts_count"
     * Purpose: A denormalized counter used for performance optimization. 
     * By storing this count directly on the Topic model, the application can 
     * render topic lists with reply counts without executing expensive 
     * COUNT(*) aggregate queries on the posts/replies table for every single 
     * row. This value should be kept in sync via database triggers or 
     * application-level increments whenever a new reply is posted.
     */
    @JsonProperty("posts_count")
    public int postsCount;
}