/**
 * Package: com.forum.models
 * 
 * This package contains the core domain models and data transfer objects (DTOs) 
 * used throughout the forum application. Classes in this package are primarily 
 * responsible for representing the state of business entities, facilitating 
 * data binding from JSON payloads (via Jackson), and mapping to database records.
 */
package com.forum.models;

/**
 * Jackson annotation used to indicate that unknown properties in the incoming 
 * JSON payload should be ignored during deserialization.
 * 
 * Architectural & Security Note: This is a critical resilience and security pattern 
 * for user-facing entities. It ensures that if a client sends unexpected or 
 * malicious additional fields (e.g., attempting to inject a "role" or "password" 
 * field during a profile update), the backend deserialization will not fail with 
 * an UnrecognizedPropertyException, nor will it accidentally bind unauthorized 
 * data. This guarantees forward and backward compatibility for the API contract 
 * while maintaining a strict boundary on what data the model actually accepts.
 */
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Represents a user entity within the forum application ecosystem.
 * 
 * This model serves as the foundational identity record for actors interacting 
 * with the system. It is utilized across multiple domains, including:
 * 1. Authentication & Authorization: Determining access rights via the 'role' field.
 * 2. Content Ownership: Linking topics, posts, and quiz attempts to a specific user.
 * 3. Account Lifecycle Management: Tracking the operational state of the account 
 *    via the 'status' field.
 * 
 * Security & Design Note: 
 * This class intentionally omits sensitive fields such as passwords, password 
 * hashes, or security tokens. This indicates that this model is designed to be 
 * safely serialized and transmitted in API responses (e.g., as a nested 'creator' 
 * object or in a user directory listing) without risking the exposure of 
 * confidential authentication credentials.
 * 
 * Serialization Behavior:
 * - Unknown JSON properties are safely ignored (@JsonIgnoreProperties).
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class User {

    /**
     * The unique, primary identifier for this user account.
     * 
     * Purpose: Typically generated by the database (e.g., auto-incrementing 
     * integer or sequence). This ID is the immutable source of truth for user 
     * identity and is used as a foreign key in related tables (e.g., Topic.creator_id, 
     * QuizAttempt.user_id) and for routing in API endpoints (e.g., /users/{id}).
     */
    public int id;

    /**
     * The display name or full name of the user.
     * 
     * Purpose: This is the primary human-readable identifier for the user within 
     * the forum's UI. It is displayed on posts, topic headers, profile pages, 
     * and leaderboards. Depending on the application's registration flow, this 
     * may represent a chosen username or a legal full name.
     */
    public String name;

    /**
     * The email address associated with this user account.
     * 
     * Purpose: Serves as the unique contact identifier and primary login credential 
     * for the account. It is used for account recovery, system notifications, and 
     * email verification flows.
     * 
     * Privacy Note: While this field is part of the core model, API endpoints 
     * should carefully evaluate whether to include this field in public-facing 
     * responses to comply with data privacy regulations (e.g., GDPR) and prevent 
     * email harvesting.
     */
    public String email;

    /**
     * The access control role assigned to this user.
     * 
     * Purpose: Drives Role-Based Access Control (RBAC) throughout the application. 
     * This string value determines what actions the user is permitted to perform 
     * (e.g., creating topics, moderating content, accessing admin panels).
     * 
     * Expected Values: Typical values include "USER", "MODERATOR", "ADMIN", or 
     * custom hierarchical roles defined by the business logic.
     */
    public String role;

    /**
     * The current operational state or lifecycle status of the user account.
     * 
     * Purpose: Allows the system to enforce account-level restrictions without 
     * deleting the user's data. This is critical for moderation, compliance, and 
     * security workflows.
     * 
     * Expected Values: Typical values include "ACTIVE" (normal operation), 
     * "PENDING" (awaiting email verification or admin approval), "SUSPENDED" 
     * (temporary restriction due to policy violations), or "DELETED" (soft-deleted 
     * for data retention compliance).
     */
    public String status;
}